### ISSUE TITLE
HyMacroExpansionError "global name 'distinct' is not defined"

### ISSUE THREAD

**Issue by actsasgeek** [bollwyvl/hy_kernel#10]
I'm having a bit of trouble getting the kernel going. If I type:

```
ipython console --kernel hy
```

or try to access a Hy kernel through the notebook. I get the following error. The entire stack trace is immense so let me know if you need more information.

```
HyMacroExpansionError:   File "/usr/local/lib/python2.7/site-packages/hy/core/macros.hy", line 182, column 1

  (if-python2
  ^----------
    (defmacro/g! yield-from [expr]
  --------------------------------
      `(do (import types)
  -----------------------
           (setv ~g!iter (iter ~expr))
  ------------------------------------
           (setv ~g!return nil)
  -----------------------------
           (setv ~g!message nil)
  ------------------------------
           (while true
  --------------------
             (try (if (isinstance ~g!iter types.GeneratorType)
  ------------------------------------------------------------
                    (setv ~g!message (yield (.send ~g!iter ~g!message)))
  ----------------------------------------------------------------------
                    (setv ~g!message (yield (next ~g!iter))))
  -----------------------------------------------------------
             (catch [~g!e StopIteration]
  --------------------------------------
               (do (setv ~g!return (if (hasattr ~g!e "value")
  -----------------------------------------------------------
                                       (. ~g!e value)
  ---------------------------------------------------
                                       nil))
  ------------------------------------------
                 (break)))))
  --------------------------
             ~g!return))
  ----------------------
    nil)
  -----^
HyMacroExpansionError: expanding `defmacro/g!': NameError("global name 'distinct' is not defined",)
```

I'm using the latest of Hy 0.11.0 and iPython 3.1.0 (installing the Hy kernel actually upgraded it from 3.0.0 to 3.1.0).

**Comment by bollwyvl** [comment]
Thanks for the report!

I think I'm a bit behind on this project: there are some fairly serious
incompatibilities with my approach (executing generated code from the AST).

I'll fire it up right now!

**Comment by actsasgeek** [comment]
Thanks for fixing this so fast.

I use Clojure at my day job but Python and Jupyter for data science-y type stuff. The discovery of Hy, toolz and your kernel has been mind blowing! Keep up the great work.

Cheers.

**Comment by bollwyvl** [comment]
Love it, thanks for the support.

Spreading the love, there is of course:
https://github.com/roryk/ipython-clojure

Not super active, but I'm not one to talk!

Toolz does look excellent: I've some colleagues that maintain their own
little packages of functional stuff, I should lean on them to submit
there... if they don't already exist there in a superior form!

**Comment by bollwyvl** [comment]
Somewhat off-topic:

I just pushed up a [hy package for atom](https://atom.io/packages/language-hy). It's super basic, but it provides enough context to be able to use [hydrogen](https://atom.io/packages/hydrogen) (no relation) with hy_kernel. Basically, work in `.hy` files, select some code and `Ctrl-alt-enter` (ymmv) to (fire up a hy kernel if need be and) run the code, then see the results. :boom: Once you're connected to the kernel, you'll get the same kind of autocomplete provided in the web notebook.
