### ISSUE TITLE
Error with `for` expression

### ISSUE THREAD

**Issue by nicolas-p** [bollwyvl/hy_kernel#9]
Using the git master version of the Hy kernel, the following expression works in the Hy REPL but not in the notebook:
```hy
(for [i (range 3)] (print i))
```
This is the error:
```hy
HyMacroExpansionError:   File "None", line 1, column 1

  (for [i (range 3)] (print i))
  ^---------------------------^
HyMacroExpansionError: `for' 'is_odd' is not defined
```

**Comment by bollwyvl** [comment]
Thanks! I'll take a look! Based on this and the other import issue, i might
have to change a lot of things. Reserved symbols are being used in
non-standard ways, generating non-standard python. I'd hate to lose all of
the free stuff, but i don't think generating the actual string of python
text, as i do now, is going to be  successful on the long run.
